name: Build Zygisk Module

on:
  push:
    paths:
      - 'zygisk/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Android NDK
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        echo "$PWD/android-ndk-r25b" >> $GITHUB_PATH

    - name: Build with ndk-build
      run: |
        cd zygisk
        ../android-ndk-r25b/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=arm64-v8a

    - name: Upload .so output
      uses: actions/upload-artifact@v3
      with:
        name: zygisk-module
        path: zygisk/libs/arm64-v8a/*.so
