name: Build Zygisk Module

on:
  push:
    paths:
      - 'zygisk/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Android NDK
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          echo "export PATH=\$PWD/android-ndk-r25b:\$PATH" >> $GITHUB_ENV

      - name: Build with ndk-build
        run: |
          cd zygisk
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_ABI=arm64-v8a NDK_APPLICATION_MK=Application.mk
