name: Build Zygisk Module

on:
  push:
    paths:
      - 'zygisk/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/android/ndk:r25b
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with ndk-build
        run: |
          cd zygisk
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk

      - name: Upload .so artifact
        uses: actions/upload-artifact@v2
        with:
          name: zygisk-lib
          path: |
            zygisk/libs/**/*.so
